export type CountryDefinition = {
  name: string;
  aliases: string[];
};

const makeCountry = (name: string, aliases: string[] = []): CountryDefinition => ({
  name,
  aliases
});

export const countries: CountryDefinition[] = [
  makeCountry('Afghanistan'),
  makeCountry('Albania'),
  makeCountry('Algeria'),
  makeCountry('Andorra'),
  makeCountry('Angola'),
  makeCountry('Antigua and Barbuda', ['Antigua']),
  makeCountry('Argentina'),
  makeCountry('Armenia'),
  makeCountry('Australia'),
  makeCountry('Austria'),
  makeCountry('Azerbaijan'),
  makeCountry('Bahamas', ['The Bahamas']),
  makeCountry('Bahrain'),
  makeCountry('Bangladesh'),
  makeCountry('Barbados'),
  makeCountry('Belarus'),
  makeCountry('Belgium'),
  makeCountry('Belize'),
  makeCountry('Benin'),
  makeCountry('Bhutan'),
  makeCountry('Bolivia', ['Bolivia (Plurinational State of)']),
  makeCountry('Bosnia and Herzegovina', ['Bosnia', 'Bosnia Herzegovina']),
  makeCountry('Botswana'),
  makeCountry('Brazil'),
  makeCountry('Brunei', ['Brunei Darussalam']),
  makeCountry('Bulgaria'),
  makeCountry('Burkina Faso'),
  makeCountry('Burundi'),
  makeCountry('Cabo Verde', ['Cape Verde']),
  makeCountry('Cambodia'),
  makeCountry('Cameroon'),
  makeCountry('Canada'),
  makeCountry('Central African Republic', ['CAR']),
  makeCountry('Chad'),
  makeCountry('Chile'),
  makeCountry('China', ["People's Republic of China", 'PRC']),
  makeCountry('Colombia'),
  makeCountry('Comoros'),
  makeCountry('Congo', ['Republic of the Congo', 'Congo Republic', 'Congo-Brazzaville']),
  makeCountry('Costa Rica'),
  makeCountry('Croatia'),
  makeCountry('Cuba'),
  makeCountry("Cote d'Ivoire", ['Ivory Coast', "Côte d'Ivoire"]),
  makeCountry('Cyprus'),
  makeCountry('Czechia', ['Czech Republic']),
  makeCountry('Democratic Republic of the Congo', [
    'DR Congo',
    'DRC',
    'Congo Democratic Republic',
    'Congo-Kinshasa'
  ]),
  makeCountry('Denmark'),
  makeCountry('Djibouti'),
  makeCountry('Dominica'),
  makeCountry('Dominican Republic'),
  makeCountry('Ecuador'),
  makeCountry('Egypt'),
  makeCountry('El Salvador'),
  makeCountry('Equatorial Guinea'),
  makeCountry('Eritrea'),
  makeCountry('Estonia'),
  makeCountry('Eswatini', ['Swaziland']),
  makeCountry('Ethiopia'),
  makeCountry('Fiji'),
  makeCountry('Finland'),
  makeCountry('France'),
  makeCountry('Gabon'),
  makeCountry('Gambia', ['The Gambia']),
  makeCountry('Georgia'),
  makeCountry('Germany'),
  makeCountry('Ghana'),
  makeCountry('Greece'),
  makeCountry('Grenada'),
  makeCountry('Guatemala'),
  makeCountry('Guinea'),
  makeCountry('Guinea-Bissau'),
  makeCountry('Guyana'),
  makeCountry('Haiti'),
  makeCountry('Honduras'),
  makeCountry('Hungary'),
  makeCountry('Iceland'),
  makeCountry('India'),
  makeCountry('Indonesia'),
  makeCountry('Iran', ['Iran (Islamic Republic of)']),
  makeCountry('Iraq'),
  makeCountry('Ireland'),
  makeCountry('Israel'),
  makeCountry('Italy'),
  makeCountry('Jamaica'),
  makeCountry('Japan'),
  makeCountry('Jordan'),
  makeCountry('Kazakhstan'),
  makeCountry('Kenya'),
  makeCountry('Kiribati'),
  makeCountry('Kuwait'),
  makeCountry('Kyrgyzstan'),
  makeCountry('Laos', ["Lao People's Democratic Republic"]),
  makeCountry('Latvia'),
  makeCountry('Lebanon'),
  makeCountry('Lesotho'),
  makeCountry('Liberia'),
  makeCountry('Libya'),
  makeCountry('Liechtenstein'),
  makeCountry('Lithuania'),
  makeCountry('Luxembourg'),
  makeCountry('Madagascar'),
  makeCountry('Malawi'),
  makeCountry('Malaysia'),
  makeCountry('Maldives'),
  makeCountry('Mali'),
  makeCountry('Malta'),
  makeCountry('Marshall Islands'),
  makeCountry('Mauritania'),
  makeCountry('Mauritius'),
  makeCountry('Mexico'),
  makeCountry('Micronesia', ['Federated States of Micronesia']),
  makeCountry('Moldova', ['Republic of Moldova']),
  makeCountry('Monaco'),
  makeCountry('Mongolia'),
  makeCountry('Montenegro'),
  makeCountry('Morocco'),
  makeCountry('Mozambique'),
  makeCountry('Myanmar', ['Burma']),
  makeCountry('Namibia'),
  makeCountry('Nauru'),
  makeCountry('Nepal'),
  makeCountry('Netherlands', ['Holland']),
  makeCountry('New Zealand'),
  makeCountry('Nicaragua'),
  makeCountry('Niger'),
  makeCountry('Nigeria'),
  makeCountry('North Korea', ['Democratic People\'s Republic of Korea', 'DPRK']),
  makeCountry('North Macedonia', ['Macedonia']),
  makeCountry('Norway'),
  makeCountry('Oman'),
  makeCountry('Pakistan'),
  makeCountry('Palau'),
  makeCountry('Panama'),
  makeCountry('Papua New Guinea', ['PNG']),
  makeCountry('Paraguay'),
  makeCountry('Peru'),
  makeCountry('Philippines'),
  makeCountry('Poland'),
  makeCountry('Portugal'),
  makeCountry('Qatar'),
  makeCountry('Romania'),
  makeCountry('Russia', ['Russian Federation']),
  makeCountry('Rwanda'),
  makeCountry('Saint Kitts and Nevis', ['St Kitts and Nevis', 'Saint Kitts']),
  makeCountry('Saint Lucia', ['St Lucia']),
  makeCountry('Saint Vincent and the Grenadines', ['St Vincent and the Grenadines']),
  makeCountry('Samoa'),
  makeCountry('San Marino'),
  makeCountry('Sao Tome and Principe', ['São Tomé and Príncipe']),
  makeCountry('Saudi Arabia'),
  makeCountry('Senegal'),
  makeCountry('Serbia'),
  makeCountry('Seychelles'),
  makeCountry('Sierra Leone'),
  makeCountry('Singapore'),
  makeCountry('Slovakia'),
  makeCountry('Slovenia'),
  makeCountry('Solomon Islands'),
  makeCountry('Somalia'),
  makeCountry('South Africa'),
  makeCountry('South Korea', ['Republic of Korea', 'Korea, South']),
  makeCountry('South Sudan'),
  makeCountry('Spain'),
  makeCountry('Sri Lanka'),
  makeCountry('Sudan'),
  makeCountry('Suriname'),
  makeCountry('Sweden'),
  makeCountry('Switzerland'),
  makeCountry('Syria', ['Syrian Arab Republic']),
  makeCountry('Tajikistan'),
  makeCountry('Tanzania', ['United Republic of Tanzania']),
  makeCountry('Thailand'),
  makeCountry('Timor-Leste', ['East Timor']),
  makeCountry('Togo'),
  makeCountry('Tonga'),
  makeCountry('Trinidad and Tobago'),
  makeCountry('Tunisia'),
  makeCountry('Turkey', ['Türkiye']),
  makeCountry('Turkmenistan'),
  makeCountry('Tuvalu'),
  makeCountry('Uganda'),
  makeCountry('Ukraine'),
  makeCountry('United Arab Emirates', ['UAE']),
  makeCountry('United Kingdom', ['UK', 'Great Britain', 'Britain']),
  makeCountry('United States', ['USA', 'US', 'United States of America', 'America']),
  makeCountry('Uruguay'),
  makeCountry('Uzbekistan'),
  makeCountry('Vanuatu'),
  makeCountry('Venezuela', ['Venezuela (Bolivarian Republic of)']),
  makeCountry('Vietnam', ['Viet Nam']),
  makeCountry('Yemen'),
  makeCountry('Zambia'),
  makeCountry('Zimbabwe')
];

export const TOTAL_COUNTRIES = countries.length;
